name: SLAMRecorder
targets:
  SLAMRecorder:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SLAMRecorder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.brett.SLAMRecorder
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        DEVELOPMENT_TEAM: ${TEAM_ID} 
        CODE_SIGN_STYLE: Automatic
    info:
      path: SLAMRecorder/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        NSCameraUsageDescription: "Camera access is required for ARKit tracking."
        NSPhotoLibraryAddUsageDescription: "Required to save recorded sessions."
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true

  SLAMRecorderTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SLAMRecorderTests
    dependencies:
      - target: SLAMRecorder
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.brett.SLAMRecorderTests